dist: xenial
language: ruby
sudo: true

rvm:
  - 2.1.1
  - 2.5.3
  - 2.6.0

matrix:
  allow_failures:
    - rvm: 2.1.1
    - rvm: 2.6.0

services:
  - postgresql
  - redis-server
before_install:
  - gem install bundler -v '1.17.3'
  - cp config/database.yml.sample config/database.yml
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script: bundle exec rspec

jobs:
  include:
    - stage: build
      name: "Build docker image"
      services:
        - docker
      install: true
      rvm: 2.5.3
      script: skip
      deploy:
        provider: script
        script: bash bin/deploy

stages:
  - tests
  - name: build
    if: branch = master AND type = push
